# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QLabel#lbl_header {\n"
"    color: #2c3e50;\n"
"    background-color: #ecf0f1;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    border: 1px solid #bdc3c7;\n"
"}\n"
"QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"QPushButton#btn_product { background-color: #2ecc71; }\n"
"QPushButton#btn_product:hover { background-color: #27ae60; }\n"
"QPushButton#btn_order { background-color: #e74c3c; }\n"
"QPushButton#btn_order:hover { background-color: #c0392b; }\n"
"QPushButton#btn_order_item { background-color: #9b59b6; }\n"
"QPushButton#btn_order_item:hover { background-color: #8e44ad; }\n"
"QPushButton#btn_payment { background-color: #f39c12; }\n"
"QPushButton#btn_payment:hover { background-color: #d35400; }\n"
"QPushButton#btn_product_sales { background-color: #1abc9c; }\n"
"QPushButton#btn_product_sales:hover { background-color: #16a085; }\n"
"QPushButton#btn_user { background-color: #3498db; }\n"
"QPushButton#btn_user:hover { background-color: #2980b9; }\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    alternate-background-color: #ecf0f1;\n"
"    selection-background-color: #3498db;\n"
"    selection-color: white;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #bdc3c7;\n"
"}\n"
"QTableWidget::item { padding: 5px; }\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #34495e;\n"
"    color: white;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QStatusBar, QMenuBar, QMenu {\n"
"    background-color: #34495e;\n"
"    color: white;\n"
"}\n"
"QMenuBar::item {\n"
"    padding: 8px 16px;\n"
"}\n"
"QMenuBar::item:selected, QMenu::item:selected {\n"
"    background-color: #2c3e50;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #3498db;\n"
"}\n"
"QLabel#lbl_user_info {\n"
"    color: #16a085;\n"
"    font-weight: bold;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_header = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")
        self.verticalLayout.addWidget(self.lbl_header)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_user_info = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lbl_user_info.setFont(font)
        self.lbl_user_info.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_user_info.setObjectName("lbl_user_info")
        self.horizontalLayout.addWidget(self.lbl_user_info)
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout.addWidget(self.btn_login)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_product = QtWidgets.QPushButton(self.centralwidget)
        self.btn_product.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_product.setFont(font)
        self.btn_product.setObjectName("btn_product")
        self.horizontalLayout_2.addWidget(self.btn_product)
        self.btn_order = QtWidgets.QPushButton(self.centralwidget)
        self.btn_order.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_order.setFont(font)
        self.btn_order.setObjectName("btn_order")
        self.horizontalLayout_2.addWidget(self.btn_order)
        self.btn_order_item = QtWidgets.QPushButton(self.centralwidget)
        self.btn_order_item.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_order_item.setFont(font)
        self.btn_order_item.setObjectName("btn_order_item")
        self.horizontalLayout_2.addWidget(self.btn_order_item)
        self.btn_payment = QtWidgets.QPushButton(self.centralwidget)
        self.btn_payment.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_payment.setFont(font)
        self.btn_payment.setObjectName("btn_payment")
        self.horizontalLayout_2.addWidget(self.btn_payment)
        self.btn_product_sales = QtWidgets.QPushButton(self.centralwidget)
        self.btn_product_sales.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_product_sales.setFont(font)
        self.btn_product_sales.setObjectName("btn_product_sales")
        self.horizontalLayout_2.addWidget(self.btn_product_sales)
        self.btn_user = QtWidgets.QPushButton(self.centralwidget)
        self.btn_user.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_user.setFont(font)
        self.btn_user.setObjectName("btn_user")
        self.horizontalLayout_2.addWidget(self.btn_user)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAdmin = QtWidgets.QMenu(self.menubar)
        self.menuAdmin.setObjectName("menuAdmin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.menuFile.addAction(self.actionExit)
        self.menuAdmin.addAction(self.actionLogin)
        self.menuAdmin.addAction(self.actionLogout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAdmin.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ứng Dụng Quản Lý Đặt Đồ Ăn Online"))
        self.lbl_header.setText(_translate("MainWindow", "Admin Dashboard"))
        self.lbl_user_info.setText(_translate("MainWindow", "Chưa đăng nhập"))
        self.btn_login.setText(_translate("MainWindow", "Đăng nhập"))
        self.btn_product.setText(_translate("MainWindow", "Sản phẩm"))
        self.btn_order.setText(_translate("MainWindow", "Đơn hàng"))
        self.btn_order_item.setText(_translate("MainWindow", "Chi tiết đơn hàng"))
        self.btn_payment.setText(_translate("MainWindow", "Thanh toán"))
        self.btn_product_sales.setText(_translate("MainWindow", "Thống kê doanh thu"))
        self.btn_user.setText(_translate("MainWindow", "Người dùng"))
        self.menuFile.setTitle(_translate("MainWindow", "Thoát"))
        self.menuAdmin.setTitle(_translate("MainWindow", "Admin"))
        self.actionExit.setText(_translate("MainWindow", "Đồng Ý"))
        self.actionLogin.setText(_translate("MainWindow", "Đăng nhập"))
        self.actionLogout.setText(_translate("MainWindow", "Đăng xuất"))
