# Generated by Django 5.1.5 on 2025-04-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Món ăn'), ('drink', 'Nước uống')], default='food', max_length=10),
        ),
    ]
