# Generated by Django 5.1.5 on 2025-04-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Món ăn'), ('drink', 'Nước uống'), ('fast food', 'Thức ăn nhanh')], default='food', max_length=10),
        ),
    ]
