# Generated by Django 5.1.5 on 2025-04-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Thẻ ngân hàng'), ('wallet', 'Ví điện tử')], max_length=20),
        ),
    ]
