# Generated by Django 5.1.5 on 2025-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Thẻ ngân hàng'), ('Wallet', 'Ví điện tử')], max_length=20),
        ),
    ]
