# Generated by Django 5.1.5 on 2025-04-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_order_estimated_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_time',
        ),
    ]
