# Generated by Django 5.1.5 on 2025-04-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_order_delivery_status_order_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
    ]
