# Generated by Django 5.1.5 on 2025-04-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
