# Generated by Django 5.1.5 on 2025-04-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_user_membership_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Thẻ ngân hàng'), ('Wallet', 'Ví điện tử'), ('Membership', 'Điểm thành viên')], max_length=20),
        ),
    ]
