# Generated by Django 5.1.5 on 2025-05-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CurrentAccount', 'Tài khoản hiện có'), ('Membership', 'Điểm thành viên')], max_length=20),
        ),
    ]
